### ISSUE TITLE
Add to spigot website.... (please)

### ISSUE THREAD

**Issue by SoaringGecko** [Delta2Force/McMultimedia#1]
It's not really an issue but I can't make a pull request so.... could you please add this to the <a style="color:red" href="https://www.spigotmc.org/">Spigot website</a>? (This deserves more love..... also my server provider only lets me get plugins from Spigot or Bukkit because it doesn't have ftp support)

**Comment by delta2force** [comment]
Im doing this after school today.

**Comment by SoaringGecko** [comment]
Ok thank you, I really appreciate it.

**Comment by delta2force** [comment]
Just did it :)
