### ISSUE TITLE
Sorry, once again not a real issue just wanted to ask you a question

### ISSUE THREAD

**Issue by SoaringGecko** [Delta2Force/McMultimedia#3]
I was just wondering if would mind me putting this repository on a website that lists all my repository... except it'll be in a section called something like "cool things made by other people" (not sure what I'll call label it as) I'll also specify it was you who made it on the page, but I can't guarantee it'll look good though... I'm not the best with CSS3...
If you look at the repository I'm almost entirely changing how it looks, it'll look like [this](https://drive.google.com/file/d/1yX9edC1sT47z2tkcWJoJxLYD2JlpuJg1/view?usp=sharing) not [this](https://drive.google.com/file/d/1uCw5ax6XIxTVGitULaCIjSbfdUaB14M-/view?usp=sharing)

edit: I already changed how it looks... just didn't add the "cool things made by other people" part... for obvious reasons. If you want to look at it [here you go.](https://soaringgecko.github.io/SoaringGecko-Repositories/)

**Comment by delta2force** [comment]
Sorry, forgot about this issue...
I don't mind at all!

**Comment by SoaringGecko** [comment]
Ok cool I will add that a.s.a.p.
